executor: android
environment:
  FLUTTER_VERSION: "3.0.1"
  FLUTTER_CHANNEL: "stable"
steps:
  - checkout:
      path: app
  - flutter/install_sdk_and_pub:
      flutter_version: 3.0.1 
  - format
  - analyze
  - test
  - build-android
  